### ISSUE TITLE
Improper change of elasticsearch.indices behavior.

### ISSUE THREAD

**Issue by Semtexcz** [oarepo/oarepo-mapping-includes#2]
This package change behavior of elasticsearch.indices behavior. If I want to create new index with command es.indices.create(index="some_index", ignore=400), I get KeyError: 'body'. But body should not be required parameter. 

Whole Traceback:

Traceback (most recent call last):
  File "/home/semtex/Projekty/nusl/venv/bin/invenio", line 10, in <module>
    sys.exit(cli())
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/semtex/Projekty/nusl/invenio-nusl-taxonomies/invenio_nusl_taxonomies/cli.py", line 210, in reindex
    current_search_client.indices.create(index=index_, ignore=400)
  File "/home/semtex/Projekty/nusl/venv/lib/python3.7/site-packages/invenio_oarepo_mapping_includes/config.py", line 73, in create
    _resolve_mappings(kwargs['body'])
KeyError: 'body'

**Comment by mesemus** [comment]
implementation completely rewritten, should not be a problem anymore
